### ISSUE TITLE
Expose configuration options to pass to istanbul

### ISSUE THREAD

**Issue by plumlee** [devongovett/browserify-istanbul#10]
First, thanks for a great tool. It's solved an issue that I've spent days on - how to get code coverage of the source files versus the browserified ones.

I'm using http://theintern.io as the testing framework for our application. It uses a custom `coverageVariable` of `__internCoverage`, and also uses the `noCompact: true` option.  I'd like to be able to pass those directly to browserify-istanbul as configuration params, but the current format doesn't allow it. 

Would you be open to a change/pull request that creates the instrumenter inside the transform function, so that options such as the `coverageVariable` could then be passed through to the istanbul.Instrumenter instantiation call?

**Comment by plumlee** [comment]
Bump.

**Comment by plumlee** [comment]
Not much activity on any of the issues here - perhaps the other people have dropped theie issues. Would you be interested in giving contributor rights to others to help add new features, or is a fork the best long term solution?

**Comment by devongovett** [comment]
Merged #11.
