### ISSUE TITLE
Browserify transforms order?

### ISSUE THREAD

**Issue by StevenLangbroek** [devongovett/browserify-istanbul#12]
I'm trying to get this to work with 6to5ify, but am running into an issue:

If I add 'browserify-istanbul' to my list of browserify transform in my karma.conf.js, I can only apply it to all files (including my specs, because they need to be run through browserify as well). This is my karma.conf.js:

```js
module.exports = function(karma){
  karma.set({
    frameworks: ["browserify", "mocha", "chai-sinon"],
    browserify: {
      debug: true,
      extensions: [".js", ".hbs"],
      transform: ["6to5ify", "hbsfy", "browserify-istanbul"]
    },
    reporters: ["dots", "osx", "junit", "coverage"],
    coverageReporter: {
      type: "text"
    },
    junitReporter: {
      outputFile: "spec/reports/test-results.xml"
    },
    preprocessors: {
      "src/javascript/**/*": ["browserify"],
      "spec/**/*": ["browserify"]
    },
    browsers: ["PhantomJS"],
    files: ["spec/unit/**/*Spec.js"],
    logLevel: "LOG_DEBUG",
    autoWatch: true
  });
};
```

I'm sure I'm doing something wrong here, but I can't figure out the proper way of instrumenting in this case.

**Comment by bendrucker** [comment]
This is how browserify transforms work. Filtering is left up to each individual package if it needs to implement it. You'll need to add your spec glob to ignore option otherwise those files will get instrumented. For an example on how to specific transform options in karma-browserify, see https://github.com/nikku/karma-browserify#transforms

**Comment by StevenLangbroek** [comment]
So, I have it sort of working, had to "hack" it a bit in my `karma.conf.js`:

```js
    browserify: {
      debug: false,
      extensions: [".js", ".hbs"],
      configure: function(bundle){
        bundle.on('prebundle', function(){
          bundle
            .transform(to5ify)
            .transform(hbsfy)
            .transform(cover(coverOptions));
        });
      }
    },
```

I've closed the ticket, hope someone else who's having the same problem can find it here.

**Comment by bendrucker** [comment]
You can certainly configure your transforms manually. But if you read my suggestion you can get your original code working with a one line change.
