### ISSUE TITLE
worth adding 'bower_components' to default ignore?

### ISSUE THREAD

**Issue by peter-mouland** [devongovett/browserify-istanbul#17]
is there an occasion when you would want to instrument bower_components?
Am i right in thinking these are external dependencies, or do people user bower for other use cases?

I suggest this because i get a timeout with my tests when using this transform within karma without using:
`istanbul({ ignore: ['**/bower_components/**']  })`

**Comment by devongovett** [comment]
I haven't really used bower, but this sounds reasonable to me. If you make a pull request, I'll merge it.
