### ISSUE TITLE
There should be a place to tell you that this thing is great

### ISSUE THREAD

**Issue by steffansluis** [devongovett/browserify-istanbul#20]
I had been searching for a way to get file specific coverage for about an hour or 6. We use CommonJS and browserify, so up until now we just had coverage of our bundle. Finally, I found your post [here] (https://github.com/englishtown/buster-istanbul/pull/6), and through there I found this repo. Changing about 10 lines in my Gruntfile gave me what I have been looking for, so I would really like to thank you for making the world a better place! Feel free to close or delete this issue, since it's not really an issue, however I can imagine there are more people who's day you have made or will in the future, so yeah. Anyways, thanks!

**Comment by devongovett** [comment]
Thanks, it's nice to hear this! Glad you find it useful. :smile:
