### ISSUE TITLE
Cannot Ignore Code with /* istanbul ignore next */

### ISSUE THREAD

**Issue by johnnyshankman** [devongovett/browserify-istanbul#24]
Unfortunately I am finding that the directive `/* istanbul ignore next */` does nothing, unlike in the standard version of Istanbul.

I want to use it to ignore require statements like I would in Istanbul since they are messing with my code coverage.

Here is the [documentation](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md) for ignoring code in Istanbul's repo.

Here is my transform in `karma.conf`

```
transform: [ 'rewireify', babelify, istanbul({
        ignore: [
        '**/spec/**',
        '**/node_modules/**',
        '**/app/js/config.js'
      ],
}) ],
```

And here is what I'm attempting to do

```
'use strict';

/* istanbul ignore next */
var CardView = require('./card');
```

I'd love to have this feature, as it is _really_ useful in large apps.

Without it it becomes very difficult to figure out what is and is not actually covered in the file itself as opposed to what is not covered inside the required-in files.

**Comment by zdychacek** [comment]
Hi,

will be this issue solved?

I would appreciate this.

Thanks in advance,

O.

**Comment by alexindigo** [comment]
Hey, sorry for the delay. We've switched to the latest istanbul, actually it's using istanbul from your installation, so it supposed to work same way. Do you mind to double check with the latest version of `browserify-istanbul`?

Thank you.

**Comment by matrunchyk** [comment]
Same happens to me. Seems like neither `istanbul ignore next` or `istanbul ignore if` works.
I'm using it along with Cypress + Vue. Also, in some files instrumentation/coverage report is broken. Example:

![image](https://user-images.githubusercontent.com/2089828/166442360-0ca2b92d-768d-422e-8a2b-6d122bc46d62.png)

**Comment by johnnyshankman** [comment]
closing this because it's so old. hopefully you have solved this by now or someone opens a new issue. i no longer use istanbul for anything.
