### ISSUE TITLE
Update istanbul version

### ISSUE THREAD

**Issue by feross** [devongovett/browserify-istanbul#26]
The version of `istanbul` that is used is quite a bit out-of-date. There are also npm install warnings that go away if you update the latest version.

```
npm WARN prefer global istanbul@0.2.16 should be installed with -g
```

**Comment by joeMalmsten** [comment]
Agreed, could the istanbul version please be updated. Currently when using browserify-istanbul I consistently reproduce the below issue.

https://github.com/gotwarlost/istanbul/issues/476

**Comment by devongovett** [comment]
Now uses the istanbul version installed by your application.
