### ISSUE TITLE
`istanbul` should not be `require()`d if `options.instrumenter` is set

### ISSUE THREAD

**Issue by zaygraveyard** [devongovett/browserify-istanbul#33]
I use `babel-istanbul`, but since this library calls `require('istanbul')` at the beginning, I'm forced to install "istanbul" even if I'm not using it.

I suggest the change I made in the "index.js" file of the #29.

**Comment by alexindigo** [comment]
Oh, I see. Do you mind to resubmit the PR with just `require` change?
Thank you.

**Comment by zaygraveyard** [comment]
@alexindigo is the PR good?
Thank you
