### ISSUE TITLE
browserify-istanbul + istanbul traceur

### ISSUE THREAD

**Issue by ouhouhsami** [devongovett/browserify-istanbul#7]
Hello, 

I'd like to use istanbul-traceur (https://www.npmjs.org/package/istanbul-traceur) with browserify-istanbul. 
The modificiation could be very small to browserify-istanbul code, as we could pass the instrumenter as an option.

Would you accept a PR in this direction ?

```
var instrumenter = instrumenter in options ? options.instrumenter : new istanbul.Instrumenter();
```

Cheers

**Comment by devongovett** [comment]
#14 was merged and adds support for custom instrumenters.
